export function createUserZone12Props(ctx) {
  const {
    ZONE12_FILTERS,
    zone12Filter,
    setZone12Filter,
    zone12Counts,
    zone12ZeroAnalysisSummary,
    zone12HighlightTerms,
    zone12TopNoiseReasons,
    zone12FilteredRows,
    zone12StatusForRow,
    extractZone12Hashtags,
    zone12TermHits,
    zone12ExcludeTerms,
    opinionRowClass,
    getScoreForDisplay,
    scoreDisplayMode,
    scoreAxisHeader,
    axisLabels,
    sortLabel,
    handleSort,
    renderHighlightedZone12Text,
    JP_UI_LABELS,
    zone12ReasonForRow,
    viewMode,
    NOISE_CATEGORY_LABELS,
    safeRuntimeText,
    sortKey,
    sortDirection,
  } = ctx;

  return {
    sortKey,
    sortDirection,
    filters: ZONE12_FILTERS,
    activeFilter: zone12Filter,
    onFilterChange: setZone12Filter,
    counts: zone12Counts,
    zeroAnalysisSummary: zone12ZeroAnalysisSummary,
    highlightTerms: zone12HighlightTerms,
    topNoiseReasons: zone12TopNoiseReasons,
    filteredRows: zone12FilteredRows,
    getStatusForRow: zone12StatusForRow,
    getHashtagsForRow: extractZone12Hashtags,
    getTermHits: zone12TermHits,
    excludeTerms: zone12ExcludeTerms,
    getOpinionRowClass: opinionRowClass,
    getScoreForDisplay,
    scoreDisplayMode,
    scoreAxisHeader,
    axisLabels,
    sortLabel,
    onSort: handleSort,
    renderHighlightedText: renderHighlightedZone12Text,
    labels: JP_UI_LABELS,
    getReasonForRow: zone12ReasonForRow,
    viewMode,
    noiseCategoryLabels: NOISE_CATEGORY_LABELS,
    safeRuntimeText,
  };
}
