export function createUserZone11Props(ctx) {
  const {
    JP_UI_LABELS,
    axisLabels,
    currentOpinionCount,
    formatPercent,
    formatScore,
    getScoreForDisplay,
    personaAAnalysisMemoItems,
    personaMode,
    qualityLabel,
    queryDiagnosisLabel,
    result,
    safeRuntimeText,
    scoreAxisHeader,
    scoreConcentrationMessages,
    scoreDisplayMode,
    stagedCurrentDataCount,
    stagedFetchState,
    stagedNextFetchCount,
    stagedRemainingCount,
    truncateText,
    userFeedback,
    userReferenceGraphMessage,
    userReferenceGraphWarning,
    viewMode,
    zone11DisplayTitle,
  } = ctx;

  return {
    personaMode,
    viewMode,
    title: zone11DisplayTitle,
    result,
    currentOpinionCount,
    userFeedback,
    stagedFetchState,
    stagedCurrentDataCount,
    stagedRemainingCount,
    stagedNextFetchCount,
    scoreConcentrationMessages,
    axisLabels,
    scoreDisplayMode,
    userReferenceGraphWarning,
    userReferenceGraphMessage,
    JP_UI_LABELS,
    personaAAnalysisMemoItems,
    safeRuntimeText,
    queryDiagnosisLabel,
    formatPercent,
    qualityLabel,
    formatScore,
    truncateText,
    scoreAxisHeader,
    getScoreForDisplay,
  };
}
