import { createUserDashboardProps } from "./createUserDashboardProps.js";
export function createUserDashboardPayload(scope = {}) {
  const {
    compactDashboardLabel,
    currentAnalysisPurposeConfig,
    currentBatchCount,
    currentClusterDisplayLabel,
    currentDataCount,
    currentOpinionCount,
    currentPersonaConfig,
    currentSessionSampleLabel,
    currentXDataStateLabel,
    dashboardActionHeight,
    dashboardActionPanelRef,
    dashboardCompactIndicators,
    dashboardContent,
    dashboardCountBreakdownIndicators,
    dashboardHeight,
    dashboardLabel,
    dashboardLeftWidth,
    dashboardPanelRef,
    dashboardPublishIndicators,
    dashboardStatusHeight,
    dashboardStatusItems,
    dashboardStatusPanelRef,
    height,
    onDashboardResizeStart,
    onSidebarResizeStart,
    operation,
    operationStatus,
    operationStatusClass,
    operationTimeLabel,
    panelRef,
    publishIndicators,
    showPublishGroup,
    sidebarContent,
    sidebarWidth,
    status,
    statusIndicators,
    statusItemTitle,
    statusItems,
    zone0StatusChipClass,
    zone0VersionLabel,
  } = scope;

  return createUserDashboardProps({
      compactDashboardLabel, currentAnalysisPurposeConfig, currentBatchCount: typeof currentBatchCount === "undefined" ? undefined : currentBatchCount, currentClusterDisplayLabel, currentDataCount: typeof currentDataCount === "undefined" ? undefined : currentDataCount, currentOpinionCount, currentPersonaConfig, currentSessionSampleLabel, currentXDataStateLabel, dashboardActionPanelRef, dashboardCompactIndicators, dashboardContent: typeof dashboardContent === "undefined" ? undefined : dashboardContent, dashboardCountBreakdownIndicators, dashboardActionHeight, dashboardHeight, dashboardLeftWidth, dashboardLabel: typeof dashboardLabel === "undefined" ? undefined : dashboardLabel, dashboardPanelRef, dashboardPublishIndicators, dashboardStatusHeight, dashboardStatusItems, dashboardStatusPanelRef, height: typeof height === "undefined" ? undefined : height, onDashboardResizeStart: typeof onDashboardResizeStart === "undefined" ? undefined : onDashboardResizeStart, onSidebarResizeStart: typeof onSidebarResizeStart === "undefined" ? undefined : onSidebarResizeStart, operation: typeof operation === "undefined" ? undefined : operation, operationStatus, operationStatusClass, operationTimeLabel, panelRef: typeof panelRef === "undefined" ? undefined : panelRef, publishIndicators: typeof publishIndicators === "undefined" ? undefined : publishIndicators, showPublishGroup: typeof showPublishGroup === "undefined" ? undefined : showPublishGroup, sidebarContent: typeof sidebarContent === "undefined" ? undefined : sidebarContent, sidebarWidth, status: typeof status === "undefined" ? undefined : status, statusIndicators: typeof statusIndicators === "undefined" ? undefined : statusIndicators, statusItems: typeof statusItems === "undefined" ? undefined : statusItems, statusItemTitle, zone0StatusChipClass, zone0VersionLabel,
    });
}
