export default function UserSidebarAxisSection({ axisSectionProps }) {
  const {
    AXIS_PRESETS,
    JP_UI_LABELS,
    analysisMode,
    applyAxisConfig,
    axisDirty,
    axisLowDescriptionAutoGenerated,
    axisQualityWarnings,
    axisStatus,
    canRescoreWithCurrentAxis,
    draftAxisConfig,
    inferLowAxisDescription,
    operationStatus,
    rescoreButtonText,
    rescoreWithCurrentAxis,
    result,
    scoreDisplayMode,
    selectAxisPreset,
    setScoreDisplayMode,
    updateDraftAxis,
    viewMode,
  } = axisSectionProps;

  return (
    <section className="row card axis-config-card zone-card zone-2" data-zone="2-axis">
      <div className="zone-heading">Zone 2 評価軸設定</div>
      {viewMode === "developer" && <div className="zone-order-marker developer-panel-badge">表示順 5 / Zone 2</div>}
      <details open>
        <summary>評価軸を編集</summary>
        <div className="axis-config-content">
          <p className="zone-lead">Zone 2 では評価軸とスコア表示だけを扱います。</p>
          <p className="axis-policy-note">
            評価モード: {analysisMode === "axisDriven" ? "評価軸に合わせて取得" : "広めに探索"}
          </p>

          <div className="axis-preset-buttons">
            {Object.entries(AXIS_PRESETS)
              .filter(([key]) => key !== "themeDefault")
              .map(([key, preset]) => (
                <button
                  key={key}
                  type="button"
                  className={
                    draftAxisConfig.presetKey === key
                      ? "option-button option-button-selected axis-preset-button"
                      : "option-button axis-preset-button"
                  }
                  onClick={() => selectAxisPreset(key)}
                >
                  {preset.label}
                </button>
              ))}
          </div>

          {["x", "y", "z"].map((axis) => (
            <div key={axis} className="axis-edit-group">
              <label>
                {axis.toUpperCase()}軸ラベル
                <input
                  value={draftAxisConfig[axis].label}
                  onChange={(event) => updateDraftAxis(axis, "label", event.target.value)}
                />
              </label>
              <label>
                {axis.toUpperCase()}軸の高い説明
                <textarea
                  value={draftAxisConfig[axis].description}
                  onChange={(event) => updateDraftAxis(axis, "description", event.target.value)}
                />
              </label>
              <label>
                {axis.toUpperCase()}軸の低い説明
                <textarea
                  className={
                    axisLowDescriptionAutoGenerated[axis]
                      ? "axis-low-description-textarea auto-generated"
                      : "axis-low-description-textarea manual"
                  }
                  value={draftAxisConfig[axis].lowDescription || ""}
                  placeholder={inferLowAxisDescription(draftAxisConfig[axis].description, draftAxisConfig[axis].label)}
                  onChange={(event) => updateDraftAxis(axis, "lowDescription", event.target.value)}
                />
              </label>
              {axisLowDescriptionAutoGenerated[axis] && draftAxisConfig[axis].lowDescription && (
                <div className="axis-auto-low-description">
                  {JP_UI_LABELS.autoGeneratedLowDescription}: {draftAxisConfig[axis].lowDescription}
                </div>
              )}
            </div>
          ))}

          <div className="axis-config-actions">
            <button
              type="button"
              className={
                operationStatus.applyAxis.status === "running"
                  ? "action-button action-button-primary is-running"
                  : operationStatus.applyAxis.status === "success" && !axisDirty
                    ? "action-button action-button-primary is-done"
                    : "action-button action-button-primary"
              }
              onClick={applyAxisConfig}
            >
              {operationStatus.applyAxis.status === "running"
                ? "評価軸を適用中..."
                : operationStatus.applyAxis.status === "success" && !axisDirty
                  ? "評価軸適用済み"
                  : "評価軸を適用"}
            </button>
            <button
              type="button"
              className={
                operationStatus.rescore.status === "running"
                  ? "action-button action-button-secondary is-running"
                  : operationStatus.rescore.status === "success" && !axisDirty
                    ? "action-button action-button-secondary is-done"
                    : "action-button action-button-secondary"
              }
              onClick={rescoreWithCurrentAxis}
              disabled={!canRescoreWithCurrentAxis}
            >
              {operationStatus.rescore.status === "running"
                ? "再スコアリング中..."
                : operationStatus.rescore.status === "success" && !axisDirty
                  ? "再スコアリング済み"
                  : rescoreButtonText}
            </button>
          </div>

          <div className="score-display-mode-panel">
            <strong>スコア表示</strong>
            <div className="analysis-mode-buttons">
              {[
                ["absolute", "絶対スコア"],
                ["relative", "相対スコア"],
              ].map(([value, label]) => (
                <button
                  key={value}
                  type="button"
                  className={scoreDisplayMode === value ? "option-button option-button-selected" : "option-button"}
                  onClick={() => setScoreDisplayMode(value)}
                >
                  {label}
                </button>
              ))}
            </div>
            <div className="status-panel">
              現在のグラフ表示: {result.resolvedScoreDisplayMode === "relative" ? "相対スコア" : "絶対スコア"}
            </div>
          </div>

          {axisStatus && <div className="axis-status">{axisStatus}</div>}
          {axisQualityWarnings.length > 0 && (
            <div className="query-axis-warning">
              <strong>評価軸の注意</strong>
              {axisQualityWarnings.map((warning, index) => (
                <div key={`axis-quality-${index}`}>{warning}</div>
              ))}
            </div>
          )}
        </div>
      </details>
    </section>
  );
}
